// AUTO-GENERATED byte-identical twin of ./god-rays.vertex.glsl
// The .glsl file holds the verbatim original shader (see its own header line).
// Next.js cannot import *.glsl as raw text without a next.config.mjs rule, so the
// exact same bytes are re-exported here as a String.raw template. Never hand-edit
// only one copy - scripts/verify-scene-params.mjs asserts the two stay identical.
export const godRaysVertex = String.raw`// Extracted verbatim from evidence\source-assets\js\app\page-4c279de0997d388f.js module 2551 (334 chars)
// Evidence: CONFIRMED-BUNDLE (original site GLSL source, minified bundle string literal)
precision highp float;

uniform float uTime;


varying vec2 vUv;
varying vec3 vPosition;



void main() {
    vec3 pos = position.xyz;
    vec4 modelViewPosition = modelViewMatrix * vec4(pos, 1.0);
    vec4 finalPos = projectionMatrix * modelViewPosition;

    vUv = uv;
    vPosition=position.xyz;

    gl_Position = finalPos;
    
}`;

export default godRaysVertex;
