// AUTO-GENERATED byte-identical twin of ./postfx-noise.vertex.glsl
// The .glsl file holds the verbatim original shader (see its own header line).
// Next.js cannot import *.glsl as raw text without a next.config.mjs rule, so the
// exact same bytes are re-exported here as a String.raw template. Never hand-edit
// only one copy - scripts/verify-scene-params.mjs asserts the two stay identical.
export const postfxNoiseVertex = String.raw`// Extracted verbatim from evidence\source-assets\js\596-40a806be0d0d2bb3.js module 5593 (186 chars, offset 52212)
// Evidence: CONFIRMED-BUNDLE (original site GLSL source, minified bundle string literal)
// Role: vertex shader of the custom noise/"split" post-processing pass (paired with postfx-noise.fragment.glsl / module 4291)
precision highp float;
varying vec2 vUv;

void main() {
    vUv = uv;
    gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
}`;

export default postfxNoiseVertex;
