// AUTO-GENERATED byte-identical twin of ./postfx-glitch.fragment.glsl
// The .glsl file holds the verbatim original shader (see its own header line).
// Next.js cannot import *.glsl as raw text without a next.config.mjs rule, so the
// exact same bytes are re-exported here as a String.raw template. Never hand-edit
// only one copy - scripts/verify-scene-params.mjs asserts the two stay identical.
export const postfxGlitchFragment = String.raw`// Extracted verbatim from evidence\source-assets\js\app\page-4c279de0997d388f.js module 255 (1417 chars)
// Evidence: CONFIRMED-BUNDLE (original site GLSL source, minified bundle string literal)
uniform float uFade;

uniform sampler2D uDiffuse1;

uniform float uGlitchAmount;
uniform float uDarkenFactor;
uniform vec2 uDistortion;
uniform float uGlitchMultiplier;
uniform float uShiftMultiplier;

varying vec2 vUv;

void main() {
	vec2 vUvOffset = vec2(0. + uDistortion.x, 0. + uDistortion.y) * uGlitchMultiplier;
	vec2 vUvTexel1 = vUv + vUvOffset * 0.005 * uGlitchAmount;

	float shiftOffset = 0.005 * uShiftMultiplier;

	vec4 texel1 = texture2D( uDiffuse1, vUvTexel1 );
	vec4 texel1r = texture2D( uDiffuse1, vec2(vUvTexel1.x + shiftOffset, vUvTexel1.y) );
	vec4 texel1g = texture2D( uDiffuse1, vec2(vUvTexel1.x, vUvTexel1.y +shiftOffset) );
	vec4 texel1b = texture2D( uDiffuse1, vec2(vUvTexel1.x - shiftOffset, vUvTexel1.y - shiftOffset) );

	vec4 glitchedTexel1 = vec4(texel1r.r, texel1g.g, texel1b.b, texel1.a);
	glitchedTexel1.rgb *= 1.0 - uDarkenFactor; 
	vec4 glitchyScene1 = mix(texel1, glitchedTexel1, uGlitchAmount);

	vec4 emptyColor = vec4(0., 0., 0., 0.);

	gl_FragColor = mix( glitchyScene1, emptyColor, uFade );

	// if (useTexture==1) {

	// 	vec4 transitionTexel = texture2D( tMixTexture, vUv );
	// 	float r = mixRatio * (1.0 + threshold * 2.0) - threshold;
	// 	float mixf=clamp((transitionTexel.r - r)*(1.0/threshold), 0.0, 1.0);

	// 	gl_FragColor = mix( texel1, texel2, mixf );

	// } else {

	// 	gl_FragColor = mix( texel2, texel1, mixRatio );

	// }

	#include <colorspace_fragment>;

}
`;

export default postfxGlitchFragment;
