// AUTO-GENERATED byte-identical twin of ./postfx-noise.fragment.glsl
// The .glsl file holds the verbatim original shader (see its own header line).
// Next.js cannot import *.glsl as raw text without a next.config.mjs rule, so the
// exact same bytes are re-exported here as a String.raw template. Never hand-edit
// only one copy - scripts/verify-scene-params.mjs asserts the two stay identical.
export const postfxNoiseFragment = String.raw`// Extracted verbatim from evidence\source-assets\js\app\page-4c279de0997d388f.js module 4291 (2883 chars)
// Evidence: CONFIRMED-BUNDLE (original site GLSL source, minified bundle string literal)
precision highp float;

uniform sampler2D tDiffuse;
uniform float time;
uniform float uNoiseDensityThreshold;
uniform float uNoiseAlpha;
varying vec2 vUv;
uniform vec2 res;
uniform float intensity;
uniform vec2 uTextureResolution;

float random(vec2 co){
    return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);
}
vec2 coverMapping( float imgRatio, float targetRatio, vec2 currentUv){
    vec2 newUv = currentUv;

    float yRatio = imgRatio / targetRatio;
    float xRatio = targetRatio / imgRatio;

    newUv.y *= yRatio;
    newUv.y += (1. - yRatio) * 0.5;

    newUv.x *= xRatio;
    newUv.x += (1. - xRatio) * 0.5;

    return imgRatio < targetRatio ? vec2(currentUv.x, newUv.y) : vec2(newUv.x, currentUv.y);
}

vec4 blur( vec2 uv, float blurSize, float offset) {

	const float MAX_ITERATIONS = 6.28318530718;
    const float Directions = 10.0;
    const float Quality = 2.0;
    float Size = blurSize;
    vec2 Radius = Size/res;
    vec4 Color = texture2D(tDiffuse, uv);

    for( float d=0.0; d< MAX_ITERATIONS; d+=6.28318530718/Directions)
    {
		for(float i=1.0/Quality; i<=1.0; i+=1.0/Quality)
        {
			Color += texture2D( tDiffuse, uv+vec2(cos(d+offset),sin(d+offset))*Radius*i);
        }
    }

    Color /= Quality * Directions - 7.0;
    return Color;
}

float threshold(float num, float thresh){
	return max(num - thresh, 0.) * (1./(1.-thresh));
}


void main() {

	vec4 pixel = texture2D(tDiffuse, vUv);
	float t = floor(time*60.)/60.;
	vec2 oord = floor(vUv * ( res * 2.) ) / res;

	float rand = random( vec2(oord.x, sin(mod(t,10.)+oord.y)) );


	pixel.a = 1.;

	float d = distance(vUv, vec2(0.5));
	float sd = d;
	d *= 2.6;
	d -= .3;
	d = clamp(d,0.,1.);
	float mixVal = intensity * threshold(d, 0.6);


	if(intensity > .0){


		sd = threshold(d, 0.4);

		float r = texture2D(tDiffuse, vUv + (vec2(1.)/ res )* 3.* sd * intensity ).r;
		float g = texture2D(tDiffuse, vUv + (vec2(1.)/ res )* -3.* sd * intensity ).g;
		float b = pixel.b;

		pixel.rgb = vec3(r,g,b);
	}



	if(mixVal > 0.){
		vec4 blurred = blur( vUv, mixVal* ( 15. * rand + 10.), rand * 3.14);
		blurred.a = 1.;
		pixel = mix(pixel,blurred , mixVal);
	}

	// add some texture on top
	float ratio=uTextureResolution.x/uTextureResolution.y;
    float targetRatio=res.x/res.y;

    vec2 uv=vUv;
    uv=coverMapping(ratio,targetRatio,uv);

	vec4 noisePixel;

	// added a sin to prevent time becoming too big and creating patterns in the random noise.
	float noiseValue = random(uv*.84+mod(time,.5)) * random(uv.yx * .94+mod(time*.3,.3));//random(uv+ sin(mod(time,.5)));

	float threshold = uNoiseDensityThreshold;

	vec4 noise = vec4(noiseValue, noiseValue, noiseValue, 1.0);
	vec4 black = vec4(0.0, 0.0, 0.0, 0.0);
	noisePixel = mix(noise, black, sign(noiseValue - threshold));

	pixel += noisePixel * uNoiseAlpha;
	//


    gl_FragColor = pixel;

	#include <colorspace_fragment>;
}
`;

export default postfxNoiseFragment;
